### ISSUE TITLE
Cache Module

### ISSUE THREAD

**Issue by rodrigorar** [rodrigorar/biplane#12]
Implement the module for the Caches based on Concurrent Map.
This module contemplates 2 types of default caches:
- Simple Cache (No Cache Loader defined, memory only, and entries are managed by the client)
- Loading Cache (Cache loader defined, has access to a database of some sort, entries can be created be loading of values from the database).
This should either be based on the Bridge or Proxy design pattern so has to allow the diferent evolution of the internal and external (api) cache implementations.

**Comment by rodrigorar** [comment]
### Task List

- [ ] Implement Cache Interface
- [ ] Implement Loading Cache
- [ ] Implement Simple Cache
- [ ] Implement Internal Loading Cache
- [ ] Implement Internal Simple Cache
- [ ] Implement Cache Entry
