### ISSUE TITLE
Eviction Policy Module

### ISSUE THREAD

**Issue by rodrigorar** [rodrigorar/biplane#14]
Implement the eviction policy module for the caches, there will be two types of default eviction policies,
time based eviction policy, and usage based eviction policy. This contemplates the implementation of the eviction policy executer. This should probably be based on the Visitor design pattern.

**Comment by rodrigorar** [comment]
### Task List

- [ ] Eviction Policy Interface
- [ ] Time Based Eviction Policy
- [ ] Time Based Eviction Policy Unit Tests
- [ ] Usage Based Eviction Policy 
- [ ] Usage Based Eviction Policy Unit Tests
